# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ef_oceanpro.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'ef_oceanpro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65\x66_oceanpro.proto\"\x8e\x02\n\x0eOceanProStatus\x12\x16\n\x0epcl_pwr_offset\x18\x35 \x01(\x02\x12\x19\n\x10pow_get_sys_load\x18\x84\x04 \x01(\x02\x12\x17\n\x0epow_get_bp_cms\x18\x86\x04 \x01(\x02\x12\x18\n\x0f\x62\x61ttery_soc_x10\x18\x8c\x02 \x01(\x05\x12\x14\n\x0bgrid_vol_l1\x18\xb7\x0b \x01(\x02\x12\x14\n\x0bgrid_amp_l1\x18\xb8\x0b \x01(\x02\x12\x14\n\x0bgrid_vol_l2\x18\xb9\x0b \x01(\x02\x12\x14\n\x0bgrid_amp_l2\x18\xba\x0b \x01(\x02\x12\x14\n\x0bgrid_pow_l1\x18\xbb\x0b \x01(\x02\x12\x14\n\x0bgrid_pow_l2\x18\xbc\x0b \x01(\x02\x12\x12\n\tmisc_1682\x18\x92\r \x01(\x05\"7\n\x0fOceanProSysInfo\x12\x0e\n\x06pv_pwr\x18\x15 \x01(\x02\x12\x14\n\x0csys_load_pwr\x18\x16 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ef_oceanpro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCEANPROSTATUS']._serialized_start=22
  _globals['_OCEANPROSTATUS']._serialized_end=292
  _globals['_OCEANPROSYSINFO']._serialized_start=294
  _globals['_OCEANPROSYSINFO']._serialized_end=349
# @@protoc_insertion_point(module_scope)
