from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ChannelSampleInfo(_message.Message):
    __slots__ = ("voltage", "reactive_pwr", "current")
    VOLTAGE_FIELD_NUMBER: _ClassVar[int]
    REACTIVE_PWR_FIELD_NUMBER: _ClassVar[int]
    CURRENT_FIELD_NUMBER: _ClassVar[int]
    voltage: float
    reactive_pwr: float
    current: float
    def __init__(self, voltage: _Optional[float] = ..., reactive_pwr: _Optional[float] = ..., current: _Optional[float] = ...) -> None: ...

class ChannelStatus(_message.Message):
    __slots__ = ("enabled", "ev_config", "max_amps", "position", "name", "flag", "index")
    ENABLED_FIELD_NUMBER: _ClassVar[int]
    EV_CONFIG_FIELD_NUMBER: _ClassVar[int]
    MAX_AMPS_FIELD_NUMBER: _ClassVar[int]
    POSITION_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    FLAG_FIELD_NUMBER: _ClassVar[int]
    INDEX_FIELD_NUMBER: _ClassVar[int]
    enabled: int
    ev_config: bytes
    max_amps: float
    position: int
    name: str
    flag: int
    index: bytes
    def __init__(self, enabled: _Optional[int] = ..., ev_config: _Optional[bytes] = ..., max_amps: _Optional[float] = ..., position: _Optional[int] = ..., name: _Optional[str] = ..., flag: _Optional[int] = ..., index: _Optional[bytes] = ...) -> None: ...

class SmartPanel40Status(_message.Message):
    __slots__ = ("pcl_pwr_offset", "utc_timezone_id", "pow_get_sys_grid", "pow_get_sys_load", "pow_get_pv_sum", "pow_get_bp_cms", "pow_get_load_output_sum", "pow_get_sys_load_from_pv", "pow_get_sys_load_from_bp", "pow_get_sys_load_from_grid", "pow_get_standby_generator", "pow_get_portable_generator", "cms_chg_rem_time", "cms_batt_store_energy", "cms_batt_pow_in_remain", "grid_connection_vol_l1", "grid_connection_vol_l2", "grid_connection_amp_l1", "grid_connection_amp_l2", "grid_connection_freq_period_l1", "grid_connection_freq_period_l2", "grid_connection_power_l1", "grid_connection_power_l2", "grid_connection_reactive_power_l1", "grid_connection_reactive_power_l2", "grid_connection_apparent_power_l1", "grid_connection_apparent_power_l2", "panel_bus_vol_l1", "panel_bus_vol_l2", "dt_pv_pwr_current", "dt_pv2_pwr_current", "dt_pv3_pwr_current", "dt_pv4_pwr_current", "dt_pv5_pwr_current", "dt_pv6_pwr_current", "dt_pv7_pwr_current", "dt_pv8_pwr_current", "dev_temperature_1", "dev_temperature_2", "dev_temperature_3", "dev_temperature_4", "dev_temperature_5", "load_ch1_sta", "load_ch2_sta", "load_ch3_sta", "load_ch4_sta", "load_ch5_sta", "load_ch6_sta", "load_ch7_sta", "load_ch8_sta", "load_ch9_sta", "load_ch10_sta", "load_ch11_sta", "load_ch12_sta", "load_ch13_sta", "load_ch14_sta", "load_ch15_sta", "load_ch16_sta", "load_ch17_sta", "load_ch18_sta", "load_ch19_sta", "load_ch20_sta", "load_ch21_sta", "load_ch22_sta", "load_ch23_sta", "load_ch24_sta", "load_ch25_sta", "load_ch26_sta", "load_ch27_sta", "load_ch28_sta", "load_ch29_sta", "load_ch30_sta", "load_ch31_sta", "load_ch32_sta", "load_ch33_sta", "load_ch34_sta", "load_ch35_sta", "load_ch36_sta", "load_ch37_sta", "load_ch38_sta", "load_ch39_sta", "load_ch40_sta", "load_ch1_sample_info", "load_ch2_sample_info", "load_ch3_sample_info", "load_ch4_sample_info", "load_ch5_sample_info", "load_ch6_sample_info", "load_ch7_sample_info", "load_ch8_sample_info", "load_ch9_sample_info", "load_ch10_sample_info", "load_ch11_sample_info", "load_ch12_sample_info", "load_ch13_sample_info", "load_ch14_sample_info", "load_ch15_sample_info", "load_ch16_sample_info", "load_ch17_sample_info", "load_ch18_sample_info", "load_ch19_sample_info", "load_ch20_sample_info", "load_ch21_sample_info", "load_ch22_sample_info", "load_ch23_sample_info", "load_ch24_sample_info", "load_ch25_sample_info", "load_ch26_sample_info", "load_ch27_sample_info", "load_ch28_sample_info", "load_ch29_sample_info", "load_ch30_sample_info", "load_ch31_sample_info", "load_ch32_sample_info", "load_ch33_sample_info", "load_ch34_sample_info", "load_ch35_sample_info", "load_ch36_sample_info", "load_ch37_sample_info", "load_ch38_sample_info", "load_ch39_sample_info", "load_ch40_sample_info")
    PCL_PWR_OFFSET_FIELD_NUMBER: _ClassVar[int]
    UTC_TIMEZONE_ID_FIELD_NUMBER: _ClassVar[int]
    POW_GET_SYS_GRID_FIELD_NUMBER: _ClassVar[int]
    POW_GET_SYS_LOAD_FIELD_NUMBER: _ClassVar[int]
    POW_GET_PV_SUM_FIELD_NUMBER: _ClassVar[int]
    POW_GET_BP_CMS_FIELD_NUMBER: _ClassVar[int]
    POW_GET_LOAD_OUTPUT_SUM_FIELD_NUMBER: _ClassVar[int]
    POW_GET_SYS_LOAD_FROM_PV_FIELD_NUMBER: _ClassVar[int]
    POW_GET_SYS_LOAD_FROM_BP_FIELD_NUMBER: _ClassVar[int]
    POW_GET_SYS_LOAD_FROM_GRID_FIELD_NUMBER: _ClassVar[int]
    POW_GET_STANDBY_GENERATOR_FIELD_NUMBER: _ClassVar[int]
    POW_GET_PORTABLE_GENERATOR_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_STORE_ENERGY_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_POW_IN_REMAIN_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_VOL_L1_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_VOL_L2_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_AMP_L1_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_AMP_L2_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_FREQ_PERIOD_L1_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_FREQ_PERIOD_L2_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_POWER_L1_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_POWER_L2_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_REACTIVE_POWER_L1_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_REACTIVE_POWER_L2_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_APPARENT_POWER_L1_FIELD_NUMBER: _ClassVar[int]
    GRID_CONNECTION_APPARENT_POWER_L2_FIELD_NUMBER: _ClassVar[int]
    PANEL_BUS_VOL_L1_FIELD_NUMBER: _ClassVar[int]
    PANEL_BUS_VOL_L2_FIELD_NUMBER: _ClassVar[int]
    DT_PV_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV2_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV3_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV4_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV5_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV6_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV7_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DT_PV8_PWR_CURRENT_FIELD_NUMBER: _ClassVar[int]
    DEV_TEMPERATURE_1_FIELD_NUMBER: _ClassVar[int]
    DEV_TEMPERATURE_2_FIELD_NUMBER: _ClassVar[int]
    DEV_TEMPERATURE_3_FIELD_NUMBER: _ClassVar[int]
    DEV_TEMPERATURE_4_FIELD_NUMBER: _ClassVar[int]
    DEV_TEMPERATURE_5_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH1_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH2_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH3_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH4_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH5_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH6_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH7_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH8_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH9_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH10_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH11_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH12_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH13_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH14_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH15_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH16_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH17_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH18_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH19_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH20_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH21_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH22_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH23_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH24_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH25_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH26_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH27_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH28_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH29_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH30_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH31_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH32_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH33_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH34_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH35_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH36_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH37_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH38_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH39_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH40_STA_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH1_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH2_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH3_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH4_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH5_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH6_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH7_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH8_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH9_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH10_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH11_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH12_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH13_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH14_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH15_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH16_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH17_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH18_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH19_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH20_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH21_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH22_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH23_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH24_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH25_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH26_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH27_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH28_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH29_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH30_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH31_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH32_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH33_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH34_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH35_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH36_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH37_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH38_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH39_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    LOAD_CH40_SAMPLE_INFO_FIELD_NUMBER: _ClassVar[int]
    pcl_pwr_offset: float
    utc_timezone_id: str
    pow_get_sys_grid: float
    pow_get_sys_load: float
    pow_get_pv_sum: float
    pow_get_bp_cms: float
    pow_get_load_output_sum: float
    pow_get_sys_load_from_pv: float
    pow_get_sys_load_from_bp: float
    pow_get_sys_load_from_grid: float
    pow_get_standby_generator: float
    pow_get_portable_generator: float
    cms_chg_rem_time: int
    cms_batt_store_energy: int
    cms_batt_pow_in_remain: int
    grid_connection_vol_l1: float
    grid_connection_vol_l2: float
    grid_connection_amp_l1: float
    grid_connection_amp_l2: float
    grid_connection_freq_period_l1: float
    grid_connection_freq_period_l2: float
    grid_connection_power_l1: float
    grid_connection_power_l2: float
    grid_connection_reactive_power_l1: float
    grid_connection_reactive_power_l2: float
    grid_connection_apparent_power_l1: float
    grid_connection_apparent_power_l2: float
    panel_bus_vol_l1: float
    panel_bus_vol_l2: float
    dt_pv_pwr_current: float
    dt_pv2_pwr_current: float
    dt_pv3_pwr_current: float
    dt_pv4_pwr_current: float
    dt_pv5_pwr_current: float
    dt_pv6_pwr_current: float
    dt_pv7_pwr_current: float
    dt_pv8_pwr_current: float
    dev_temperature_1: float
    dev_temperature_2: float
    dev_temperature_3: float
    dev_temperature_4: float
    dev_temperature_5: float
    load_ch1_sta: ChannelStatus
    load_ch2_sta: ChannelStatus
    load_ch3_sta: ChannelStatus
    load_ch4_sta: ChannelStatus
    load_ch5_sta: ChannelStatus
    load_ch6_sta: ChannelStatus
    load_ch7_sta: ChannelStatus
    load_ch8_sta: ChannelStatus
    load_ch9_sta: ChannelStatus
    load_ch10_sta: ChannelStatus
    load_ch11_sta: ChannelStatus
    load_ch12_sta: ChannelStatus
    load_ch13_sta: ChannelStatus
    load_ch14_sta: ChannelStatus
    load_ch15_sta: ChannelStatus
    load_ch16_sta: ChannelStatus
    load_ch17_sta: ChannelStatus
    load_ch18_sta: ChannelStatus
    load_ch19_sta: ChannelStatus
    load_ch20_sta: ChannelStatus
    load_ch21_sta: ChannelStatus
    load_ch22_sta: ChannelStatus
    load_ch23_sta: ChannelStatus
    load_ch24_sta: ChannelStatus
    load_ch25_sta: ChannelStatus
    load_ch26_sta: ChannelStatus
    load_ch27_sta: ChannelStatus
    load_ch28_sta: ChannelStatus
    load_ch29_sta: ChannelStatus
    load_ch30_sta: ChannelStatus
    load_ch31_sta: ChannelStatus
    load_ch32_sta: ChannelStatus
    load_ch33_sta: ChannelStatus
    load_ch34_sta: ChannelStatus
    load_ch35_sta: ChannelStatus
    load_ch36_sta: ChannelStatus
    load_ch37_sta: ChannelStatus
    load_ch38_sta: ChannelStatus
    load_ch39_sta: ChannelStatus
    load_ch40_sta: ChannelStatus
    load_ch1_sample_info: ChannelSampleInfo
    load_ch2_sample_info: ChannelSampleInfo
    load_ch3_sample_info: ChannelSampleInfo
    load_ch4_sample_info: ChannelSampleInfo
    load_ch5_sample_info: ChannelSampleInfo
    load_ch6_sample_info: ChannelSampleInfo
    load_ch7_sample_info: ChannelSampleInfo
    load_ch8_sample_info: ChannelSampleInfo
    load_ch9_sample_info: ChannelSampleInfo
    load_ch10_sample_info: ChannelSampleInfo
    load_ch11_sample_info: ChannelSampleInfo
    load_ch12_sample_info: ChannelSampleInfo
    load_ch13_sample_info: ChannelSampleInfo
    load_ch14_sample_info: ChannelSampleInfo
    load_ch15_sample_info: ChannelSampleInfo
    load_ch16_sample_info: ChannelSampleInfo
    load_ch17_sample_info: ChannelSampleInfo
    load_ch18_sample_info: ChannelSampleInfo
    load_ch19_sample_info: ChannelSampleInfo
    load_ch20_sample_info: ChannelSampleInfo
    load_ch21_sample_info: ChannelSampleInfo
    load_ch22_sample_info: ChannelSampleInfo
    load_ch23_sample_info: ChannelSampleInfo
    load_ch24_sample_info: ChannelSampleInfo
    load_ch25_sample_info: ChannelSampleInfo
    load_ch26_sample_info: ChannelSampleInfo
    load_ch27_sample_info: ChannelSampleInfo
    load_ch28_sample_info: ChannelSampleInfo
    load_ch29_sample_info: ChannelSampleInfo
    load_ch30_sample_info: ChannelSampleInfo
    load_ch31_sample_info: ChannelSampleInfo
    load_ch32_sample_info: ChannelSampleInfo
    load_ch33_sample_info: ChannelSampleInfo
    load_ch34_sample_info: ChannelSampleInfo
    load_ch35_sample_info: ChannelSampleInfo
    load_ch36_sample_info: ChannelSampleInfo
    load_ch37_sample_info: ChannelSampleInfo
    load_ch38_sample_info: ChannelSampleInfo
    load_ch39_sample_info: ChannelSampleInfo
    load_ch40_sample_info: ChannelSampleInfo
    def __init__(self, pcl_pwr_offset: _Optional[float] = ..., utc_timezone_id: _Optional[str] = ..., pow_get_sys_grid: _Optional[float] = ..., pow_get_sys_load: _Optional[float] = ..., pow_get_pv_sum: _Optional[float] = ..., pow_get_bp_cms: _Optional[float] = ..., pow_get_load_output_sum: _Optional[float] = ..., pow_get_sys_load_from_pv: _Optional[float] = ..., pow_get_sys_load_from_bp: _Optional[float] = ..., pow_get_sys_load_from_grid: _Optional[float] = ..., pow_get_standby_generator: _Optional[float] = ..., pow_get_portable_generator: _Optional[float] = ..., cms_chg_rem_time: _Optional[int] = ..., cms_batt_store_energy: _Optional[int] = ..., cms_batt_pow_in_remain: _Optional[int] = ..., grid_connection_vol_l1: _Optional[float] = ..., grid_connection_vol_l2: _Optional[float] = ..., grid_connection_amp_l1: _Optional[float] = ..., grid_connection_amp_l2: _Optional[float] = ..., grid_connection_freq_period_l1: _Optional[float] = ..., grid_connection_freq_period_l2: _Optional[float] = ..., grid_connection_power_l1: _Optional[float] = ..., grid_connection_power_l2: _Optional[float] = ..., grid_connection_reactive_power_l1: _Optional[float] = ..., grid_connection_reactive_power_l2: _Optional[float] = ..., grid_connection_apparent_power_l1: _Optional[float] = ..., grid_connection_apparent_power_l2: _Optional[float] = ..., panel_bus_vol_l1: _Optional[float] = ..., panel_bus_vol_l2: _Optional[float] = ..., dt_pv_pwr_current: _Optional[float] = ..., dt_pv2_pwr_current: _Optional[float] = ..., dt_pv3_pwr_current: _Optional[float] = ..., dt_pv4_pwr_current: _Optional[float] = ..., dt_pv5_pwr_current: _Optional[float] = ..., dt_pv6_pwr_current: _Optional[float] = ..., dt_pv7_pwr_current: _Optional[float] = ..., dt_pv8_pwr_current: _Optional[float] = ..., dev_temperature_1: _Optional[float] = ..., dev_temperature_2: _Optional[float] = ..., dev_temperature_3: _Optional[float] = ..., dev_temperature_4: _Optional[float] = ..., dev_temperature_5: _Optional[float] = ..., load_ch1_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch2_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch3_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch4_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch5_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch6_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch7_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch8_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch9_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch10_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch11_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch12_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch13_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch14_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch15_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch16_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch17_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch18_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch19_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch20_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch21_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch22_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch23_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch24_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch25_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch26_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch27_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch28_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch29_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch30_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch31_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch32_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch33_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch34_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch35_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch36_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch37_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch38_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch39_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch40_sta: _Optional[_Union[ChannelStatus, _Mapping]] = ..., load_ch1_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch2_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch3_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch4_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch5_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch6_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch7_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch8_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch9_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch10_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch11_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch12_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch13_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch14_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch15_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch16_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch17_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch18_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch19_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch20_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch21_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch22_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch23_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch24_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch25_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch26_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch27_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch28_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch29_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch30_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch31_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch32_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch33_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch34_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch35_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch36_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch37_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch38_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch39_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ..., load_ch40_sample_info: _Optional[_Union[ChannelSampleInfo, _Mapping]] = ...) -> None: ...
